### ISSUE TITLE
Have you considered json schema?

### ISSUE THREAD

**Issue by albertoabellagarcia** [openrepair/data#6]
It looks to me that 
https://github.com/openrepair/data/blob/master/quests/printers/tableschema.json

is doing what is already available using json schema format,

What is the reason to 'create tableschema.json this way and not directly into json schema?

Thanks

**Comment by zenlan** [comment]
The tableschema file came from the concept by [Frictionless Data](https://frictionlessdata.io/) some time ago. This file is merely a way to communicate the CSV data structure, data types and metadata relating to the dataset. 

The regular export of the Open Repair data is scripted and outputs datasets in both CSV and JSON formats, along with "tableschema" and README files. Quest data is infrequent, the exports are not scripted and nobody has ever asked for it in JSON format. Can't see a reason to not provide JSON, will put the idea in our backlog and see what the team thinks. It will no doubt depend on time and budget.

**Comment by albertoabellagarcia** [comment]
I like you mention frictionless data because [we](https://smartdatamodels.org) already mapped frictionless data and if I am not wrong they have already json schemas. We adapted them at the [smart data models](https://smartdatamodels.org) with their agreement. You can see [here https://github.com/smart-data-models/dataModel.FrictionlessData](https://github.com/smart-data-models/dataModel.FrictionlessData). 

We held a call with some colleagues of open repair and we would be ready to help with the creation of these json schemas as long as there would be some use case in JSON. If there is only CSV we could consider it as well.  

After that, we create also export the examples in CSV, JSON, JSON-LD and for the structure, we export in YAML, SQL, and depending on the model DTDL and geojson features. 
Additionally, we translate the definitions to be available not only in English but also in FR, DE, SP, JP, IT, and ZH (Chinese).

**Comment by ngm** [comment]
Hi Alberto, thanks for the interest!  Could you elaborate further what benefits / use cases JSON schema might support?  If there is a compelling use case for providing JSON schema in addition to / instead of tableschema.json we would happily consider it.   But at present as we have limited resources we couldn't commit to that long-term without a clear reason to do so.

**Comment by albertoabellagarcia** [comment]
If I were you I would not do a migration because it is good enough for the current utilization on your side. 
What advantages of json schema? In my opinion, the most important is that there [are many libraries in different programming languages](https://json-schema.org/implementations.html#validators)  and online services (like [this one](https://www.jsonschemavalidator.net/) we use ) that can validate if a payload is compliant and therefore you can provide certainty to the users or they can use their own validators.

At [SmartDataModels](https://smartdatamodels.org) we have developed scripts that based on the descriptions in a json schema generate 
1)  a markdown specification ([like these in 7 languages](https://github.com/smart-data-models/dataModel.Agrifood/tree/master/AgriCrop/doc)) , 
2) Populates all the attributes and include them [in a database](https://smartdatamodels.org/index.php/export-of-database-of-attributes-of-the-smart-data-models/).
3) Generate a @context 
4) Creates a [searchable form](https://smartdatamodels.org/index.php/ddbb-of-properties-descriptions/) for a wordpress site
5) With a bit more we created a [python package](https://pypi.org/project/pysmartdatamodels/) with all the json schemas
and quite a few more..

**Comment by ngm** [comment]
Thanks @albertoabellagarcia , I appreciate your thoughts on this, and good to know about those potential uses.  It sounds like it could be worth exploring when we come to a point of wanting to provide end-users with more options to use the data themselves.  As you mention I think for now providing CSV/JSON and allowing people to work with that themselves is good enough, but as demand grows we can explore this further.  Thanks!
